version: "3"
services:
  api:
    container_name: premise-api
    image: premise-api
    restart: always
    build: .
    ports:
      - "7777:7777"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - '27018:27017'
